#!/bin/bash
# Script to help connect to the dev container

echo "🔍 Dev Container Setup Instructions"
echo "=================================="
echo ""
echo "Your dev container is ready! Here's how to connect:"
echo ""
echo "Option 1: Using VS Code Command Palette"
echo "1. Press Ctrl+Shift+P (or Cmd+Shift+P on Mac)"
echo "2. Type 'Dev Containers: Attach to Running Container'"
echo "3. Select the container: vsc-mining_reliability_db-..."
echo ""
echo "Option 2: Using VS Code Remote-Containers"
echo "1. Press Ctrl+Shift+P (or Cmd+Shift+P on Mac)"
echo "2. Type 'Dev Containers: Reopen in Container'"
echo "3. VS Code should automatically detect the .devcontainer folder"
echo ""
echo "Option 3: Manual Connection"
echo "Container ID: b5d7ab0c40dd"
echo "You can connect to this container directly"
echo ""
echo "Current Status:"
echo "✅ Dev Container: Running"
echo "✅ Neo4j Database: Running on ports 7474 (browser) and 7687 (bolt)"
echo "✅ Configuration: Updated and validated"
echo ""
echo "Once connected, your environment will have:"
echo "- Python 3.12"
echo "- All required dependencies"
echo "- VS Code extensions"
echo "- Access to Neo4j database"
echo ""
echo "To test the setup once inside the container:"
echo "cd /workspaces/mining_reliability_db"
echo "python test_connection.py"
echo ""
