from setuptools import setup, find_packages

setup(
    name="mining-reliability-search",
    version="1.0.0",
    description="Advanced search algorithms for mining reliability data using Neo4j graph database",
    long_description="Sophisticated search algorithms and pattern discovery tools specifically designed for mining reliability data analysis. Features include graph-based search, Cypher query interface with safety validation, cross-facility pattern discovery, and stakeholder-focused query templates.",
    packages=find_packages(),
    install_requires=[
        "neo4j>=5.0.0",
        "dash>=2.15.0",
        "dash-bootstrap-components>=1.5.0",
        "plotly>=5.17.0",
        "pandas>=2.0.0",
        "python-dotenv>=1.0.0",
        "pydantic>=2.0.0",
        "numpy>=1.24.0",
        "scipy>=1.10.0",
        "scikit-learn>=1.3.0",
        "structlog>=23.1.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Engineers",
        "Intended Audience :: Developers",
        "Topic :: Scientific/Engineering :: Information Analysis",
        "Topic :: Database :: Database Engines/Servers",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    keywords="mining reliability search algorithms neo4j graph database pattern discovery",
    author="Mining Reliability Team",
    project_urls={
        "Documentation": "https://github.com/your-org/mining-reliability-search/docs",
        "Source": "https://github.com/your-org/mining-reliability-search",
        "Tracker": "https://github.com/your-org/mining-reliability-search/issues",
    },
)
